### ISSUE TITLE
500 Internal Server error when handling WSS connection up grade.

### ISSUE THREAD

**Issue by travestynv** [jcchavezs/coraza-http-wasm-traefik#16]
Hi,  
I am implementing the WASM plugin and Traefik to secure a Web portal that has a real-time dashboard that requires Websockets. I have the routes, authentication, and services working until I try to enable the Coraza WAF middleware. 

When there is an attempt to upgrade the connection, every minute until client session is closed or expires, I get a 500 error. 
``` traefik.log snip
2025-01-02T21:41:29-08:00 DBG github.com/traefik/traefik/v3/pkg/proxy/httputil/proxy.go:113 > 500 Internal Server Error error="Hijack failed on protocol switch: not a hijacker: *wasm.bufferingResponseWriter"
```
From this Traefik forum discussion it seems there are some known issues with interfaces on the transition back to Traefik. Like one side or the other is casting the response to an interface without the required Hijack method,  
https://github.com/traefik/traefik/issues/8682

This is an isolated environment so I have manually extracted and placed the WASM file from the latest upstream release. 

``` .traefik.yml
displayName: Coraza WAF
runtime: wasm
type: middleware
summary: Coraza WAF http-wasm middleware
wasmPath: coraza-http-wasm.wasm 
## testData
testData:
  directives:
    - SecRuleEngine On
    - SecDebugLog /dev/stdout
    - SecDebugLogLevel 9
    - SecRule REQUEST_URI "@streq /admin" "id:101,phase:1,log,deny,status:403"
```

``` traefik dynamic config 
http:
  middlewares:
    waf:
      plugin:
        coraza-http-wasm-traefik:
          directives:
            - SecRuleEngine On
            - SecDebugLog /dev/stdout
            - SecDebugLogLevel 9
            - SecRule REQUEST_URI "@streq /admin" "id:101,phase:1,log,deny,status:403"
```

Thanks,
Travis

**Comment by cg-sat** [comment]
According to https://github.com/corazawaf/coraza-caddy/issues/78#issuecomment-1635738505 Coroza doesn't support Websockets right now.
I ended up in disabling the coroza-http-wasm-traefik plugin for the websocket endpoint, but the other REST endpoints are still monitored:
```
http:
  routers:
    - websocket:
        rule: PathPrefix(`/backend/websocket`)
        entrypoints: https
        middlewares:
          - authelia
     - backend:
         rule: PathPrefix(`/backend`)
         entrypoints: https
         middlewares:
           - authelia
           - waf
```
Due to the priority calculation of traefik routers based on the length of the rule, the longer rule for the websocket takes precedence over the second rule.
