### ISSUE TITLE
"SecRequestBodyAccess On" breaks POST requests

### ISSUE THREAD

**Issue by Janhouse** [jcchavezs/coraza-http-wasm-traefik#8]
I am unable to `Include @coraza.conf-recommended` because setting `SecRequestBodyAccess On` seems to break all POST requests and they return error 500 and some gibberish response.

Testing with `traefik` `v3.0` and `coraza-waf` plugin `v0.2.1`

**Comment by jcchavezs** [comment]
Hi @Janhouse thanks for coming by. The extension is tested to support request body access as per its [e2e](https://github.com/jcchavezs/coraza-http-wasm/blob/main/e2e_test.go#L45) which is the standard e2e in all coraza connectors. How big is the payload you are trying to send? I think there might be something with the `@coraza.conf-recommended` that breaks the execution. Could you modify https://github.com/jcchavezs/coraza-http-wasm/blob/main/example_test.go in a PR to reproduce the failure?

**Comment by Janhouse** [comment]
I don't come from `go` background so all the nested repos and abstraction would require some learning time to write such tests.

Also I can't seem to find a test where it actually sends the successful POST request. A positive scenario where no malicious data is POSTed and a correct answer is returned.

Either it is also abstracted somewhere or there really are no tests for that. :shrug: 

The error has nothing to do with anything else in `@coraza.conf-recommended` besides `SecRequestBodyAccess On`.
Once I add that line to the configuration, every POST request is broken (incorrect response code and junk body).
I tried with different backend applications (wordpress, gitea, grafana), for none of them POST requests for logging in or anything else worked after loading this plugin.

Also it appears that traefik randomly starts using 100% of CPU power and it has to be killed, but I am not yet sure if it is the fault of this plugin, or it's a bug in traefik v3.0.0.

**Comment by Janhouse** [comment]
@jcchavezs I did some more testing and found out that it indeed works, but only when plain http is used. As soon as I enable https with letsencrypt, post requests start returning `500 internal error`.

**Comment by jcchavezs** [comment]
Are you enabling decryption on the app BEFORE coraza middleware?

José Carlos Chávez


man. 24. juni 2024 kl. 00:48 skrev Janis Jansons ***@***.***>:

**Comment by Janhouse** [comment]
What do you mean? I can not control that when using Traefik. I simply define the middlewares that I want to use.

I would assume that Traefik terminates TLS before sending anything to the middleware. And the backend app listens on port 80 and uses HTTP, so nothing to encrypt/decrypt there.

proxied test service from docker compose:
```yaml
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${BASE_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.middlewares=waf@file"
```

Middleware definition from traefik dynamic.yml config
```yaml
http:
  middlewares:
    waf:
      plugin:
        coraza-http-wasm-traefik:
          directives:
            - SecRuleEngine On
            - SecDebugLog /dev/stdout
            - SecDebugLogLevel 9
            - SecRequestBodyAccess On
            - SecRule REQUEST_URI "@streq /admin" "id:101,phase:1,log,deny,status:403"
```

Plugin section from traefik.yml

```yaml
experimental:
  plugins:
    coraza-http-wasm-traefik:
      moduleName: github.com/jcchavezs/coraza-http-wasm-traefik
      version: v0.2.2
```
